extends:
  - google

parserOptions:
  ecmaVersion: 2022
  sourceType: module

env:
  browser: true  # ブラウザ環境で実行されるコードであることを明示
  node: true
  es6: true

globals:
  XMLBuilder: true
  XMLParser: true

rules:
  # JavaScriptに特化したルールの例
  # 必要に応じて追加・調整してください

  # セミコロンのルール
  semi: error

  # オブジェクトリテラルのルール
  quote-props: error
  comma-dangle: [error, never]

  # 配列のルール
  array-bracket-spacing: error

  # その他
  no-undef: error

  space-before-function-paren: [error, always]
  space-before-blocks: [error, always]