env: standard
runtime: nodejs20
instance_class: F1
service: agent
automatic_scaling:
  target_cpu_utilization: 0.65
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_instances: 1
